ktor:
    development: true
    application:
        modules:
            - com.ruviapps.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
    jwt:
        secret: "secret"
        issuer: "http://0.0.0.0:8080/"
        audience: "http://0.0.0.0:8080/hello"
        realm: "Access to 'hello'"